### ISSUE TITLE
Percy dont receive screenshot from CircleCi 

### ISSUE THREAD

**Issue by minaairsupport** [percy/percy-webdriverio#205]
I can run Percy locally but when I commit to GitHub and CircleCi starting pull code and execute jobs, Percy don't get screenshots 
even it shows there snapshots 

```
[percy] stopping percy...
[percy] waiting for 1 snapshots to complete...
[percy] done.
[percy] finalized build #55: https://percy.io/TechMode/CircleCi_test/builds/2618111
```

**Comment by Robdel12** [comment]
Hey @minaairsupport would you be able to reach out via support (Intercom or support@percy.io) rather than GitHub issues? It looks like your builds aren't finalizing in CI (probably because Percy thinks you're running parallel builds).

**Comment by minaairsupport** [comment]
I hold it a common issue all people will face with CircleCI so I create an issue let me mail them and see Thanks

**Comment by minaairsupport** [comment]
I got this answer and its working 

I would unset PERCY_PARALLEL_TOTAL or set it to 1  -- it doesn't look like these builds need to be running in parallel. That's the reason your CircleCI Percy builds are still "receiving". They're waiting for a finalize all command to finalize all of the parallel shards. 

Once you remove or set PERCY_PARALLEL_TOTAL to 1, it should run correctly in CircleCI
