### ISSUE TITLE
Standalone support

### ISSUE THREAD

**Issue by selenium-tester** [percy/percy-webdriverio#22]
We use WebdriverIO in standalone mode for our browser tests, along with Spectron (which uses WebdriverIO underneath) for testing our Electron-based desktop apps. Is it on the road map to make this compatible with WDIO standalone? The idea behind Percy is great, and it would be nice to have the option of leveraging it as a drop-in module with config via CLI arguments, in addition to plugging into various tools directly.

**Comment by timhaines** [comment]
What happens when you run it with WDIO standalone at the moment?

**Comment by selenium-tester** [comment]
Apologies! I didn't get a notification about your comment.

Unless I'm misunderstanding, it's not possible to run Percy with WDIO standalone at all. "Standalone" in WDIO simply means not using the built-in WDIO test runner. In our case, we use WDIO with Ava. If you don't use the WDIO test runner, there's no opportunity to provide the configuration options Percy requires as shown in the docs because the wdio.conf.js file doesn't exist.

Perhaps we can define the Percy options as part of the config object in WDIO. But looking at the WDIO configuration docs, it doesn't appear the onPrepare and onComplete methods can be passed to it in this way while running standalone. I'll have to experiment.

Does that make sense? Am I missing something obvious?

**Comment by mfazekas** [comment]
@selenium-tester `onPrepare` and `onComplete` is not magic. 
`onComplete` runs before any tests were started
`onPrepare` runs after all tests were finished

I'd expect all test frameworks to have hooks for that. So you need to call this before any test started:


```
var percy = require('@percy-io/percy-webdriverio');
```

var assetLoaders = [percy.assetLoader('filesystem', { buildDir: 'compiled-assets-dir', mountPath: '/assets' })];
return percy.createBuild(assetLoaders);
```

and you need to call this after all tests ended

```
return percy.finalizeBuild();
```

One thing you have to be carefull is that `percy.createBuild(assetLoaders)`  and `percy.finalizeBuild()` returns a promise, which you should wait for.

I'm closing this now, as the above should solve the issue, let us know if it doesn't.
