### ISSUE TITLE
Ability to make percy a no-op for local builds.

### ISSUE THREAD

**Issue by Zoramite** [percy/percy-webdriverio#23]
I may be missing something from the docs or something obvious, but it would be nice to be able to have the ability to configure percy to be a no-op when running tests locally.

For example:

```js
// wdio.local.config.js
var percy = require('@percy-io/percy-webdriverio');

// Some method to make percy no do anything.
percy.noop();

// The config stays the same, but it ignores the requirement for percy tokens
// and any `browser.percySnapshot('Homepage')` are just ignored or logged 
// as being ignored.
// Also the `percy.createBuild(assetLoaders)` and `percy.finalizeBuild()` are 
// minimal no-ops.
exports.config = require('./wdio.conf.js');
```

Then when writing and debugging tests I can use the local config:

`wdio wdio.local.conf.js`

**Comment by timhaines** [comment]
@Zoramite Good call!  You may have seen our other client libraries behave this way when they integrate with tests.  We'll get percy-webdriverio updated to behave like this too.

**Comment by Zoramite** [comment]
If you have an idea of how you want the api to look I could take a stab at updating the library.

**Comment by fotinakis** [comment]
@Zoramite that'd be awesome. What our other client libraries do is very simple, they have something like an internal `isEnabled` flag, and only enable Percy if the correct env vars are present (ie. both PERCY_TOKEN and PERCY_PROJECT), otherwise percy snapshots just act as a no-op.

**Comment by Zoramite** [comment]
@fotinakis Sounds good: https://github.com/percy/percy-webdriverio/pull/24

**Comment by Zoramite** [comment]
I was using the `PERCY_ENABLE` flag that I saw in the python docs. I can also update it to check for the token and project to be set as well.

**Comment by timhaines** [comment]
Resolved in https://github.com/percy/percy-webdriverio/pull/24
