### ISSUE TITLE
Percy exec stuck forever

### ISSUE THREAD

**Issue by sunniejai** [percy/percy-webdriverio#326]
Version:  "@percy/webdriverio": "1.0.4"

Im running percy the way that it's described in the docs. By using "percy exec -- wdio run wdio.conf.js". However, I noticed that sometimes the build is getting stuck forever when percy is stopping.

Here are some logs from the CI

>     Spec Files:   15 passed, 2 failed, 17 total (100% completed) in 00:18:59 
> 16:53:59
>      [36m [0m
> 16:53:59
>     [percy] stopping percy...     [36m[ [35mpercy [39m] stopping percy... [0m
> 16:53:59
>     [percy] waiting for 73 snapshots to complete...

How do I go about fixing this issue? I've already tried setting the maxInstances to 1 so that nothing runs in parralel

**Comment by wwilsman** [comment]
Hi @sunniejai!

During that waiting phase, it is actually waiting for the snapshots to finish uploading. So if it's hanging on this step, then something in the network might be causing those requests to hang. If you're able to view network requests during that phase, you should be able to see which endpoint specifically is hanging. Most commonly, we've seen that firewalls might be the cause of this.
