### ISSUE TITLE
Receiving empty screenshots

### ISSUE THREAD

**Issue by mattdell** [percy/percy-webdriverio#472]
I've been dealing with this issue for the last 2 days. For some reason Percy is capturing empty screenshots.

This is one example:

<img width="1698" alt="Screenshot 2021-05-27 at 19 11 58" src="https://user-images.githubusercontent.com/2536442/119876313-a8b11100-bf1f-11eb-940e-0bb390fd85bd.png">

The code is quite simple

```
before(async function beforeAll() {
  this.timeout(loadWebsiteTimeout);
  await NavigateToUrlAndWaitUntilLoaded('/buy/bmw');
  await percySnapshot('clp - bmw');
});
```

Inside the navigate method

```
export const NavigateToUrlAndWaitUntilLoaded = async (url) => {
  await browser.url(url);
  await browser.waitUntil(() => $('.next-body').isExisting(), loadWebsiteTimeout);
}
```

There are no errors in the webdriver tests.

**Comment by mattdell** [comment]
For some reason it doesn't like being run in the `before` function. 🤔

When I run it like this it works well

```
it('should ...', () => {
  // assert some things
  percySnapshotSync('clp - bmw');
});
```

**Comment by Robdel12** [comment]
Hey @mattdell! This also looks like it's an issue with JavaScript within the app doing things. I can only load this snapshot with JS disabled, and this is the state that's captured: 

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/2072894/119901779-fa4fa080-bf0b-11eb-88be-34cea3e35a91.png">

With JS enabled there's a lot of JS errors:

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/2072894/119901879-17846f00-bf0c-11eb-87c6-f78f0fc9631e.png">

It _could_ be related to `percySnapshot` being called too soon (where the DOM is half formed, and the JS doesn't know what do with it on rerender).

**Comment by mattdell** [comment]
Interesting to see that! Those 400's are sort of expected in that situation, though we need to fix the status code response to be 404 (basically, there's no inventory for that manufacturer).

Is that view something I'm able to see or is it an internal tool?
